FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    git \
    build-essential \
    autotools-dev \
    libtool \
    pkg-config \
    libpcap-dev \
    libdumbnet-dev \
    zlib1g-dev \
    bison \
    flex \
    cmake \
    libluajit-5.1-dev \
    libhwloc-dev \
    libssl-dev \
    uuid-dev \
    wget \
    iputils-ping \
    iproute2 \
    nano \
    vim \
    libnetfilter-queue-dev \
    net-tools \
    libpcre2-dev \
    libpcre3-dev \
    libdnet-dev \
    libmnl-dev \
    autoconf automake\
    systemd \
    locales \
    language-pack-ko \
    liblzma-dev && \
    apt clean && \
    locale-gen ko_KR.utf8 && \
    dpkg-reconfigure locales

WORKDIR /opt

# .bashrc에 로케일 추가
RUN echo "" >> /root/.bashrc && \
    echo "# Setting Language(ko_KR.UTF-8)" >> /root/.bashrc && \
    echo "export LANGUAGE=ko_KR.UTF-8" >> /root/.bashrc && \
    echo "export LANG=ko_KR.UTF-8" >> /root/.bashrc && \
    echo "export LC_ALL=ko_KR.UTF-8" >> /root/.bashrc

# 환경 변수 즉시 적용되도록
ENV LANGUAGE=ko_KR.UTF-8
ENV LANG=ko_KR.UTF-8
ENV LC_ALL=ko_KR.UTF-8

# LibDAQ 설치
RUN git clone https://github.com/snort3/libdaq.git && \
    cd libdaq && \
    ./bootstrap && \
    ./configure && \
    make && \
    make install && \
    ldconfig

# Snort3 설치
RUN git clone https://github.com/snort3/snort3.git && \
    cd snort3 && \
    ./configure_cmake.sh --prefix=/usr/local && \
    cd build && \
    make && \
    make install && \
    ldconfig

CMD ["/bin/bash"]
